config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  authenticated :user do
    root :to => 'events#index'
  end

  devise_for :organizers, controllers: {
  sessions:      'organizers/sessions',
  passwords:     'organizers/passwords',
  registrations: 'organizers/registrations'
  }

  authenticated :organizer do
    root :to => "organizers#index"
  end
  root to: 'top#index'

  resources :users do
    collection do
      post :confirm
    end
  end
  get '/users/interests/:id', to:'users#interests'
  get '/users/bookmarks/:id', to:'users#bookmarks'
  get '/users/paticipants/:id', to:'users#paticipants'
  get '/users/followers/:id', to:'users#followers'

  resources :organizers do
    collection do
      post :confirm
    end
  end

  resources :events do
    resources :comments
    collection do
      post :confirm
    end
  end

  get 'searchUser', to:'events#searchUser'
  get 'searchOrganizer', to:'events#searchOrganizer'


  resources :interests, only: [:create, :destroy] # user can keep event as interests
  resources :bookmarks, only: [:create, :destroy]
  resources :paticipants, only: [:create, :destroy]
  resources :reactions, only: [:index, :create, :destroy]

  resources :chatusers do
    resources :chatmessages
  end
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  #validates :number, presence: true, format: { with: VALID_PHONE_REGEX }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  mount_uploader :icon, ImgNameUploader

  validates :name, presence:true
  validates :group, presence:true
  validates :sport, presence:true
  validates :number, presence:true
  validates :password, presence:true
  validates :password_confirmation, presence:true
  validates :introduction, presence:true
  validates :icon, presence:true
end

app/controllers/organizers/confirmations_controller.rb
# frozen_string_literal: true

class Organizers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/organizers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Organizers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/organizers/passwords_controller.rb
# frozen_string_literal: true

class Organizers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/organizers/registrations_controller.rb
# frozen_string_literal: true

class Organizers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/organizers/sessions_controller.rb
# frozen_string_literal: true

class Organizers::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  #def new
  # super
  #end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/organizers/unlocks_controller.rb
# frozen_string_literal: true

class Organizers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_action :authenticate_organizer!
  before_action :set_organizer, only:[:index, :show]
  before_action :set_search, only:[:index]

  def index
    @events = Event.all
  end

  def show
  end

  private

  def set_organizer
    @organizer = Organizer.find_by(id: params[:id])
  end

  def set_search
    @search = Event.ransack(params[:search])
    @finding = @search.result(distinct: true)
  end
end

app/views/organizers/index.html.erb
<%= render "layouts/admin-header"%>
<body>
	<p><%= notice %></p>
		<%= render "events/searchOrganizer-form"%>
	<div>
		<div class="row">
			<% @events.reverse_each do |event| %>
			<div class="col-xs-12 col-md-6 picture-panel">
				<div class="card" style="padding:10px">
					<div class="card-header">
				  イベント名：<%= event.title%>
          </div>
			  <div class="card-header">
				  イベント主催者:<%= event.organizer.name%>
        </div>
			  <div class="card-header">
			  	場所：<%= event.place%>
        </div>
			  <div class="card-header">
				  日程：<%= event.startdate %>
					  （申し込み期限:<%= event.duedate%>）
        </div>
			  <div class="card-header">
			  	<% if event.paticipants.count < event.number %>
            参加人数：<%= event.paticipants.count %>/<%= event.number %>
          <% else %>
            定員数に達したので、参加できません。（参加人数：<%= event.number %>）
          <% end%>
        </div>
			  <div class="card-image">
			  <% if event.image %>
				  <%= image_tag(event.image,:width=>"600", height:"500")%>
			  <% else %>
			    <%= image_tag("noimage") %>
		    <% end %>
	     </div>
		   <div class="card-header">
			 <%= event.content%>
			   <div class="picture-edit">
				   <% if  current_organizer.id == event.organizer_id  %>
				   <%= link_to '削除',  event_path(event.id), method: :delete, data:{confirm: '本当に削除しますか？'},class: 'btn btn-danger' %>
				   <%= link_to '編集',  edit_event_path(event.id), class: 'btn btn-info'  %>
            <% end %>
			   </div>
		   </div>
     </div>
  </div>
	 <% end %>
 </div>
</div>
</body>

<style>
.modal-content{
	height:150%;
	width:150%;
}
.user_info{
  border-radius: 50%;
  border: inset 4px #ff0000;
}
.card-image{
	image;
}
</style>

app/views/organizers/show.html.erb
<%= render'layouts/admin-header'%>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 col-md-6">
      <div class="wrapper">
        <div class="column profile-image">
          <div class="info">
              <% if current_organizer.id == @organizer.id %>
              <div class='userInfo_img'>
                <% if @organizer.icon.url(:thumb) %>
                  <%= image_tag @organizer.icon.url(:thumb),:size => "200*200",class: 'img-responsive' %>
                <% else %>
                  <%= image_tag "noimage.jpg" %>
                <% end %>
              </div>
              <div class='userInfo_name'>管理者名：<%= @organizer.name%></div>
              <div class='userInfo_name'>所属団体：<%= @organizer.group%></div>
              <div class='userInfo_name'>スポーツカテゴリ：<%= @organizer.sport %></div>
              <div class='userInfo_name'>電話番号：<%= @organizer.number%></div>
              <div class='userInfo_name'>紹介文:<%= @organizer.introduction %></div>
                <div class='userAction'>
                  <div class="userAction_edit userAction_common">
                    <%= link_to(content_tag(:i, "", class: 'fas fa-edit fa-2x'), edit_organizer_registration_path) %>
                    <span>プロフィール編集</span>
                  </div>
                </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-6 col-md-6">
      <div class="column cat2">
        <div class="info">
        <%= link_to "イベント管理", organizers_path,class: "btn btn-outline-danger info_bar" %><br>
        <%#= link_to(content_tag(:i, "イベント管理", class: 'btn btn-outline-danger info_bar'), :controller  => "events",:action => "manage") %><br>
        <%= link_to "新規イベント", new_event_path,class: "btn btn-outline-danger info_bar" %><br>
        </div>
      </div>
    </div>
  </div>
</div>