config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  authenticated :user do
    root :to => 'events#index'
  end

  devise_for :organizers, controllers: {
  sessions:      'organizers/sessions',
  passwords:     'organizers/passwords',
  registrations: 'organizers/registrations'
  }

  authenticated :organizer do
    root :to => "organizers#index"
  end
  root to: 'top#index'

  resources :users do
    collection do
      post :confirm
    end
  end
  get '/users/interests/:id', to:'users#interests'
  get '/users/bookmarks/:id', to:'users#bookmarks'
  get '/users/paticipants/:id', to:'users#paticipants'
  get '/users/followers/:id', to:'users#followers'

  resources :organizers do
    collection do
      post :confirm
    end
  end

  resources :events do
    resources :comments
    collection do
      post :confirm
    end
  end

  get 'searchUser', to:'events#searchUser'
  get 'searchOrganizer', to:'events#searchOrganizer'


  resources :interests, only: [:create, :destroy] # user can keep event as interests
  resources :bookmarks, only: [:create, :destroy]
  resources :paticipants, only: [:create, :destroy]
  resources :reactions, only: [:index, :create, :destroy]

  resources :chatusers do
    resources :chatmessages
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence:true
  validates :password_confirmation, presence:true

  # user has interested in event and want to share interest to other
  has_many :interests, dependent: :destroy
  has_many :interest_event, through: :interests, source: :event
  # user want to keep event in private
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_event, through: :bookmarks, source: :event
  # user will join event
  has_many :paticipants, dependent: :destroy
  has_many :paticipant_event, through: :paticipants, source: :event
  # user can follow other user
  has_many :active_reactions, foreign_key: 'follower_id', class_name: 'Reaction', dependent: :destroy
  has_many :following, through: :active_reactions, source: :followed
  # user can be followed by other user
  has_many :passive_reactions, foreign_key: 'followed_id', class_name: 'Reaction', dependent: :destroy
  has_many :followers, through: :passive_reactions, source: :follower
  # user has chat room to each user and can chat with
  has_many :chat_messages
  has_many :chat_room_users

  has_many :comments, dependent: :destroy
  has_many :comment_event, through: :comments, source: :event

  def follow!(other_user)
    active_reactions.create(followed_id: other_user.id)
  end

  def following?(other_user)
    active_reactions.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_reactions.find_by(followed_id: other_user.id).destroy
  end

  def matchers
    User.where(id: passive_reactions.select(:follower_id))
       .where(id: active_reactions.select(:followed_id))
  end

  mount_uploader :icon, ImgNameUploader
  enum sex: { 男: 0, 女: 1 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only:[:index, :show, :interests, :bookmarks, :paticipants, :followers]
  before_action :set_reaction, only:[:index,:followers]

  def index
  end

  def show
  end

  def interests
    @interests_event = @user.interest_event
  end

  def bookmarks
    @bookmarks_event = @user.bookmark_event
  end

  def paticipants
    @paticipants_event = @user.paticipant_event
  end

  def followers
    @users = User.all
    @following = @user.following
    @follower = @user.followers
  end

  def chat
    @matchers = current_user.matchers
    @following = @user.following
    @follower = @user.followers
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def set_reaction
    @reaction = Reaction.new
  end
end

app/views/users/_follow.html.erb
<div id="follow_form_<%= @user.id %>">
  <% unless current_user.following?(@user) %>
    <%= form_with(model: current_user.active_reactions.build(followed_id: @user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "友達リクエスト送信" , class: "btn adminSubmitBtn"%>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_reactions.find_by(followed_id: @user.id), method: :delete ) do |f| %>
      <%= f.submit "友達リクエスト解除", class: "btn adminSubmitBtn" %>
    <% end %>
  <% end %>
</div>

app/views/users/_user-header.html.erb
<nav class="navbar navbar-expand-lg navbar-light header-color">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
      </li>
      <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete,class: "nav-link" %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path, class: "nav-link"%></li>
        <li><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/bookmarks.html.erb
<%= render"layouts/user-header"%>
<div class='usershowPage'>
<h2>ブックマーク一覧</h2>
<div class="container">
  <div class="row">
    <% @bookmarks_event.reverse_each do |bookmark| %>
    <div class="col-xs-12 col-md-6 picture-panel"></div>
  </div>
  <div class="card" style="padding:10px">
    <div class="card-header">
      イベント名：<%= bookmark.title%>
    </div>
    <div class="card-header">
      イベント主催者:
    </div>
    <div class="card-header">
      場所：<%= bookmark.place%>
    </div>
    <div class="card-header">
      日程：<%= bookmark.startdate%>
        （申し込み期限:<%= bookmark.duedate%>）
    </div>
    <div class="card-header">
      ブックマークした人：<%= bookmark.bookmarks.count%>
    </div>
    <% if bookmark.image %>
        <%= image_tag(bookmark.image, :class =>"card-image")%>
   <% end %>
   <div class="card-header">
     <%= bookmark.content%>
   </div>
   <% end %>
</div>

app/views/users/followers.html.erb
<%= render'layouts/user-header'%>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">友達一覧</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">届いているリクエスト</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <div class="container">
      <div class="row">
        <% @users.each do |user| %>
        <div class="col-xs-12 col-md-6 picture-panel">
        <% if user.id != current_user.id %>
          <div class="card">
            <% if user.icon.url(:thumb)%>
              <%= image_tag user.icon.url(:thumb) %>
            <% else %>
              <%= image_tag ("noimage.jpg")%>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= user.name%>さん</h5>
              <h6 class="card-title">好きなスポーツ：<%= user.sport%></h6>
              <p class="card-text"><%= user.introduction%></p>
              <%= link_to 'メッセージ', chatusers_path(sender_id: current_user.id, recipient_id: user.id), method: :post,class: "chatForm_btn" %>
            </div>
          </div>
       </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
</div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
    <div class="tab-pane fade" id="follower" role="tabpanel" aria-labelledby="follower-tab">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-md-6 picture-panel"></div>
        <% @follower.reverse_each do |follower| %>
        <div class="card-group">
          <div class="card">
            <% if follower.icon.url(:thumb)%>
              <%= image_tag follower.icon.url(:thumb),:width=>"400", height:"300" %>
            <% else %>
              <%= image_tag ("noimage.jpg")%>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= follower.name%>さん</h5>
              <h6 class="card-title">好きなスポーツ：<%= follower.sport%></h6>
              <p class="card-text"><%= follower.introduction%></p>
              <%if current_user.following?(@user) %>
                <div class='btn alert-danger' id='liked'>友達になりました</div>
              <% else %>
                <%= render 'follow', {reaction: @reaction} %>
              <% end %>
           </div>
         </div>
        </div>
        <% end %>
       </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render'layouts/user-header'%>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <div class="wrapper">
        <div class="column profile-image">
          <div class="info">
            <div class="form-group" border="1">
              <% if @user.icon.url(:thumb) %>
                <%= image_tag @user.icon.url(:thumb),:width=>"400", height:"280" %>
              <% else %>
                <%= image_tag "noimage.jpg"%>
              <% end%>
            </div>
            <table class="table" style="table-layout:fixed;width:100%;" border="1">
              <colgroup>
                  <col style="width:30%;">
                  <col style="width:70%;">
              </colgroup>
            <thead>
              <tr></tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">名前:</th>
                <td style="word-wrap:break-word;"><%= @user.name%>さん</td>
              </tr>
              <tr>
                <th scope="row">興味のあるスポーツ：</th>
                <td style="word-wrap:break-word;"><%= @user.sport%></td>
              </tr>
              <tr>
                <th scope="row">自己紹介:</th>
                <td><%= @user.introduction %></td>
              </tr>
            </tbody>
          </table>
          <div class='userInfo_name'>
            <% if @user.id != current_user.id%>
              <%if current_user.following?(@user) %>
                <div class='btn alert-danger' id='liked'>友達になっています</div>
              <% else %>
                <%= render 'follow', {reaction: @reaction} %>
              <% end %>
            <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/interests.html.erb
<%= render"layouts/user-header"%>
<div class='usershowPage'>
<h2>興味あり一覧</h2>
<div class="container">
  <div class="row">
    <% @interests_event.reverse_each do |interest| %>
    <div class="col-xs-12 col-md-6 picture-panel"></div>
  </div>
  <div class="card" style="padding:10px">
    <div class="card-header">
      イベント名：<%= interest.title%>
    </div>
    <div class="card-header">
      イベント主催者:
    </div>
    <div class="card-header">
      場所：<%= interest.place%>
    </div>
    <div class="card-header">
      日程：<%= interest.startdate%>
        （申し込み期限:<%= interest.duedate%>）
    </div>
    <div class="card-header">
      興味を持っている人：<%= interest.interests.count%>
    </div>
    <% if interest.image %>
        <%= image_tag(interest.image, :class =>"card-image")%>
   <% end %>
   <div class="card-header">
     <%= interest.content%>
   </div>
   <% end %>
</div>

app/views/users/paticipants.html.erb
<%= render"layouts/user-header"%>
<div class='usershowPage'>
<h2>参加予定イベント</h2>
<div class="container">
  <div class="row">
    <% @paticipants_event.reverse_each do |paticipant| %>
    <div class="col-xs-12 col-md-6 picture-panel"></div>
  </div>
  <div class="card" style="padding:10px">
    <div class="card-header">
      イベント名：<%= paticipant.title%>
    </div>
    <div class="card-header">
      イベント主催者:
    </div>
    <div class="card-header">
      場所：<%= paticipant.place%>
    </div>
    <div class="card-header">
      日程：<%= paticipant.startdate%>
        （申し込み期限:<%= paticipant.duedate%>）
    </div>
    <div class="card-header">
      参加人数：<%= paticipant.paticipants.count%>/<%= paticipant.number%>
    </div>
    <% if paticipant.image %>
        <%= image_tag(paticipant.image, :class =>"card-image")%>
   <% end %>
   <div class="card-header">
     <%= paticipant.content%>
   </div>
   <% end %>
</div>

app/views/users/show.html.erb
<%= render'layouts/user-header'%>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 col-md-6">
      <div class="wrapper">
        <div class="column profile-image">
          <div class="info">
            <div class='userInfo_img'>
              <% if @user.icon.url(:thumb) %>
                <%= image_tag @user.icon.url(:thumb),:width=>"400", height:"300" %>
              <% else %>
                <%= image_tag "noimage.jpg"%>
              <% end%>
            </div>
            <div class='userInfo_name'><%= @user.name%>さん</div>
            <div class='userInfo_name'>興味のあるスポーツ：<%= @user.sport%></div>
            <div class='userInfo_name'><%= @user.introduction %></div>
              <% if current_user.id == @user.id %>
                <div class='userAction'>
                  <div class="userAction_edit userAction_common">
                    <%= link_to(content_tag(:i, "", class: 'fas fa-edit fa-2x'), edit_user_registration_path) %>
                    <span>プロフィール編集</span>
                  </div>
                </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-6 col-md-6">
      <div class="column cat2">
        <div class="info">
        <%= link_to "イベント一覧", events_path,class: "btn btn-outline-danger info_bar" %><br>
        <%= link_to(content_tag(:i, "参加予定イベント", class: 'btn btn-outline-danger info_bar'), :controller  => "users",:action => "paticipants") %><br>
        <%= link_to(content_tag(:i, "ブックマーク", class: 'btn btn-outline-danger info_bar'), :controller  => "users",:action => "bookmarks") %><br>
        <%= link_to(content_tag(:i, "興味あるイベント", class: 'btn btn-outline-danger info_bar'), :controller  => "users",:action => "interests") %><br>
        <%= link_to "チャット",chatusers_path,class: "btn btn-outline-danger info_bar" %><br>
        <%= link_to(content_tag(:i, "友達リクエスト", class: 'btn btn-outline-danger info_bar'), :controller  => "users",:action => "followers") %>
        </div>
      </div>
    </div>
  </div>
</div>