config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  authenticated :user do
    root :to => 'events#index'
  end

  devise_for :organizers, controllers: {
  sessions:      'organizers/sessions',
  passwords:     'organizers/passwords',
  registrations: 'organizers/registrations'
  }

  authenticated :organizer do
    root :to => "organizers#index"
  end
  root to: 'top#index'

  resources :users do
    collection do
      post :confirm
    end
  end
  get '/users/interests/:id', to:'users#interests'
  get '/users/bookmarks/:id', to:'users#bookmarks'
  get '/users/paticipants/:id', to:'users#paticipants'
  get '/users/followers/:id', to:'users#followers'

  resources :organizers do
    collection do
      post :confirm
    end
  end

  resources :events do
    resources :comments
    collection do
      post :confirm
    end
  end

  get 'searchUser', to:'events#searchUser'
  get 'searchOrganizer', to:'events#searchOrganizer'


  resources :interests, only: [:create, :destroy] # user can keep event as interests
  resources :bookmarks, only: [:create, :destroy]
  resources :paticipants, only: [:create, :destroy]
  resources :reactions, only: [:index, :create, :destroy]

  resources :chatusers do
    resources :chatmessages
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organizer

  has_many :interests, dependent: :destroy
  has_many :interest_users, through: :interests, source: :user

  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user

  has_many :paticipants, dependent: :destroy
  has_many :paticipant_users, through: :paticipants, source: :user

  has_many :comments, dependent: :destroy

  mount_uploader :image, ImgNameUploader

  def self.ransackable_attributes auth_object = nil
    %w(title place)
  end

  validates :title, presence:true
  validates :image, presence:true
  validates :content, length:{in: 1..500}, presence:true

  ## time validation
  validate :not_before_today
  validate :enddate_after_startdate
  validate :duedate_is_first

  def not_before_today
    errors.add(:startdate, 'は今日以降の日付を設定してください') if startdate.nil? || startdate < Date.today
  end

  def enddate_after_startdate
    errors.add(:enddate, 'は開始日よりも後の日程を設定してください') if enddate.nil? ||  enddate < startdate
  end

  def duedate_is_first
    errors.add(:duedate, 'は開始日よりも前に設定してください') if duedate.nil? || startdate && enddate < duedate
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only:[:show, :edit, :update, :destroy]
  before_action :set_user, only:[:show]
  before_action :set_organizer, only:[:show]
  before_action :set_search, only:[:index, :searchUser,:searchOrganizer]

  def index
    @events = Event.all
  end

  def searchUser
  end

  def searchOrganizer
  end

  def show
    @interest = current_user.interests.find_by(event_id: @event.id)
    @bookmark = current_user.bookmarks.find_by(event_id: @event.id)
    @paticipant = current_user.paticipants.find_by(event_id: @event.id)
    @user_interests = @event.interests.includes(:user).order(:created_at)
    @comments = @event.comments
    @comment = @event.comments.build
  end

  def new
    if params[:back]
      @event = Event.new(event_params)
    else
      @event = Event.new
    end
  end

  def confirm
    @event = current_organizer.events.build(event_params)
    render :new  if @event.invalid?
  end

  def create
    @event = current_organizer.events.build(event_params)
    if @event.save
       redirect_to current_organizer
    else
      render 'new'
    end
  end

  def edit
    if current_organizer.id != @event.organizer_id
      redirect_to current_organizer
    end
  end

  def update
    if @event.update(event_params)
      redirect_to current_organizer
    else
      render 'new'
    end
  end

  def destroy
    if current_organizer.id != @event.organizer_id
      redirect_back fallback_location: {action: "manage"}
    else
      @event.destroy
      redirect_back fallback_location: {action: "manage"}
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :content, :image, :image_cache, :number, :day, :startdate,:starttime, :enddate,:endtime, :duetime, :duedate)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def set_organizer
    @organizer = Organizer.find_by(id: params[:id])
  end

  def set_search_params
    params.require(:search).permit(:title_cont)
  end

  def set_search
    @search = Event.ransack(params[:q])
    @finding = @search.result(distinct: true)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_events_path
    elsif action_name == 'edit'
      event_path
    end
  end
end

app/views/events/_form.html.erb
<%= render"layouts/admin-header"%>
<div class="adminPostPage">
  <%= form_with(model: @event, local: true, url: choose_new_or_edit) do |f| %>
  <% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= @event.errors.count %>件のエラーがあります</h2>
    <ul>
        <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>
  <div class='container'>
    <header class="header">
      <div>新規イベント作成</div>
    </header>
    <label for="file_photo" class="rounded-circle userProfileImg">
      <div class="userProfileImg_description">イベントイメージをアップロード</div>
      <i class="fas fa-camera fa-3x"></i>
      <%= image_tag(@event.image.url) if @event.image.url %>
      <%= f.file_field :image, id: "file_photo" %>
    </label>
    <div class="postImgPreview" id="postImgPreview">
      <img id="thumbnail" class="postImgPreview_content" accept="image/*" src="">
      <p class="userImgPreview_text">画像をアップロード済み</p>
    </div>
    <div class="form-group">
      <label>イベント名</label>
      <%= f.text_field :title, class: "form-control", placeholder: "名前を入力してください" %>
    </div>
    <div class="form-group">
      <label>最大参加人数(1~100人)</label>
      <%= f.number_field :number,in: 1...101 %>
    </div>
    <div class="form-group">
      <label>イベント開始時間（予定）</label>
      <%= f.date_field :startdate %>
      <%= f.time_field :starttime %>
    </div>
    <div class="form-group">
      <label>イベント終了時間（予定）</label>
      <%= f.date_field :enddate %>
      <%= f.time_field :endtime %>
    </div>
    <div class="form-group">
      <label>詳細</label>
      <%= f.text_area :content, maxlength: "500",:size=>"85*400", rows:"400",class:"form-control",placeholder:"イベントの詳細を記入してください（場所や行う内容など）" %>
    </div>
    <div class="form-group">
      <label>イベント受付締め切り時間</label>
      <%= f.date_field :duedate %>
      <%= f.time_field :duetime %>
    </div>
    <div class="text-center">
      <%= f.submit  class: "btn adminSubmitBtn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/events/_interest.html.erb
<% if @interest.present? %>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    興味を持っているユーザー
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">ユーザー一覧</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body"style="height:100%;witdh:100%;">
            <% @user_interests.each do |userInterest| %>
            <% if userInterest.user.id != current_user.id %>
              <%= userInterest.user.name %>
              (<%= userInterest.user.sex %>)
              <%= link_to 'プロフィールを見る', users_path(id: userInterest.user.id), class: 'btn btn-info' %>
              <!-- 興味あるを押したユーザーだけが友達リクエストを送れるようにする-->
              <%# if @interests.present %>
                <%#= link_to '友達リクエストをキャンセルする', paticipant_path(id: @paticipant.id), method: :delete, class: 'btn btn-danger' %>
              <%# else %>
                <%#= link_to '友達リクエストを送る', paticipants_path(event_id: @event.id), method: :event, class: 'btn btn-info' %>
              <%# end %>
              <!--上記を変更する -->
              <br>
           <% end %>
           <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_reaction.html.erb
<% if @interest.present? %>
  <%= link_to '興味ありを解除する', interest_path(id: @interest.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= link_to '興味あり', interests_path(event_id: @event.id), method: :event, class: 'btn btn-info' %>
<% end %>
<% if @bookmark.present? %>
  <%= link_to 'ブックマークを解除する', bookmark_path(id: @bookmark.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= link_to 'ブックマークする', bookmarks_path(event_id: @event.id), method: :event, class: 'btn btn-info' %>
<% end %>
<% if @paticipant.present? %>
  <%= link_to '参加をキャンセルする', paticipant_path(id: @paticipant.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= link_to '参加予定にする', paticipants_path(event_id: @event.id), method: :event, class: 'btn btn-info' %>
<% end %>

app/views/events/_search-form.html.erb
<div class="card card-sm" style="margin:10px">
  <%= search_form_for @search, url: search_path do |f| %>
  <div class="card-body row no-gutters align-items-center">
    <div class="col-auto">
      <i class="fas fa-search h4 text-body"></i>
    </div><!--end of col-->
    <div class="col">
      <%= f.search_field :title_or_place_cont ,class:"form-control form-control-lg form-control-borderless",placeholder: "気になるキーワードを入力してください", :size=>"40*30"  %>
    </div><!--end of col-->
    <div class="col-auto">
      <%= f.submit "search", class:"btn btn-lg btn-success"%>
    </div><!--end of col-->
  </div>
  <% end %>
</div>

app/views/events/_searchOrganizer-form.html.erb
<div class="card card-sm" style="margin:10px">
  <%= search_form_for(@search, url: searchOrganizer_path) do |f| %>
  <div class="card-body row no-gutters align-items-center">
    <div class="col-auto">
      <i class="fas fa-search h4 text-body"></i>
    </div><!--end of col-->
    <div class="col">
      <%= f.search_field :title_cont ,class:"form-control form-control-lg form-control-borderless",placeholder: "気になるキーワードを入力してください(例,野球、初心者など)", :size=>"40*30"  %>
    </div><!--end of col-->
    <div class="col-auto">
      <%= f.submit "search", class:"btn btn-lg btn-success"%>
    </div><!--end of col-->
  </div>
  <% end %>
</div>

app/views/events/confirm.html.erb
<%= render "layouts/admin-header"%>
<div class="adminPostPage">
  <header class="header">
    <div>以下の内容で、イベントを作成する</div>
  </header>
<%= form_with(model: @event, url: events_path, local: true) do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :number %>
  <%= form.hidden_field :startdate %>
  <%= form.hidden_field :starttime %>
  <%= form.hidden_field :enddate %>
  <%= form.hidden_field :endtime %>
  <%= form.hidden_field :duedate %>
  <%= form.hidden_field :duetime %>
  <div class="form-group">
    <h2>イベント名:<%= @event.title %></h2>
      <%= image_tag(@event.image.url) %>
  </div>

  <table class="table" style="table-layout:fixed;width:100%;" border="1">
    <colgroup>
        <col style="width:20%;">
        <col style="width:80%;">
    </colgroup>
  <thead>
    <tr>
      <th scope="col">項目</th>
      <th scope="col">入力内容</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">イベント名:</th>
      <td style="word-wrap:break-word;"><%= @event.title %></td>
    </tr>
    <tr>
      <th scope="row">イベント詳細:</th>
      <td style="word-wrap:break-word;"><%= @event.content%></td>
    </tr>
    <tr>
      <th scope="row">イベント予定時間:</th>
      <td><%= @event.startdate.strftime("%Y年%m月%d日")%><%= @event.starttime.strftime("%H:%M")%>
        ~ <%= @event.enddate.strftime("%Y年%m月%d日")%><%= @event.endtime.strftime("%H:%M")%>
      </td>
    </tr>
    <tr>
      <th scope="row">イベント参加人数（最大）:</th>
      <td><%= @event.number %>人</td>
    </tr>
    <tr>
      <th scope="row">申し込み締め切り:</th>
      <td><%= @event.duedate.strftime("%Y年%m月%d日") %><%= @event.duetime.strftime("%H:%M") %>まで</td>
    </tr>
  </tbody>
</table>
  <%= form.submit  "作成する", class: "btn adminSubmitBtn" %>
<% end %>

<%= form_with(model: @event, url: new_event_path, local: true, method: 'get') do |form| %>
<%= form.hidden_field :image_cache %>
<%= form.hidden_field :title %>
<%= form.hidden_field :content %>
<%= form.hidden_field :number %>
<%= form.hidden_field :startdate %>
<%= form.hidden_field :starttime %>
<%= form.hidden_field :enddate %>
<%= form.hidden_field :endtime %>
<%= form.hidden_field :duedate %>
<%= form.hidden_field :duetime %>

  <%= form.submit "もどる",name: 'back', class: "btn" %>
<% end %>

app/views/events/edit.html.erb
<%= render "form"%>

app/views/events/index.html.erb
<%= render"layouts/user-header"%>
<%= render "index" %>

app/views/events/manage.html.erb
<%= render "layouts/admin-header"%>
<body>
	<p><%= notice %></p>
		<%= render "searchOrganizer-form"%>
	<div>
		<div class="row">
			<% @events.reverse_each do |event| %>
			<div class="col-xs-12 col-md-6 picture-panel">
				<div class="card" style="padding:10px">
					<div class="card-header">
				  イベント名：<%= event.title%>
          </div>
			  <div class="card-header">
				  イベント主催者:<%= event.organizer.name%>
        </div>
			  <div class="card-header">
			  	場所：<%= event.place%>
        </div>
			  <div class="card-header">
				  日程：<%= event.startdate %>
					  （申し込み期限:<%= event.duedate%>）
        </div>
			  <div class="card-header">
			  	<% if event.paticipants.count < event.number %>
            参加人数：<%= event.paticipants.count %>/<%= event.number %>
          <% else %>
            定員数に達したので、参加できません。（参加人数：<%= event.number %>）
          <% end%>
        </div>
			  <div class="card-image">
			  <% if event.image %>
				  <%= image_tag(event.image,:width=>"600", height:"500")%>
			  <% else %>
			    <%= image_tag("noimage") %>
		    <% end %>
	     </div>
		   <div class="card-header">
			 <%= event.content%>
			   <div class="picture-edit">
				   <% if  current_organizer.id == event.organizer_id  %>
				   <%= link_to '削除',  event_path(event.id), method: :delete, data:{confirm: '本当に削除しますか？'},class: 'btn btn-danger' %>
				   <%= link_to '編集',  edit_event_path(event.id), class: 'btn btn-info'  %>
            <% end %>
			   </div>
		   </div>
     </div>
  </div>
	 <% end %>
 </div>
</div>
</body>

<style>
.modal-content{
	height:150%;
	width:150%;
}
.user_info{
  border-radius: 50%;
  border: inset 4px #ff0000;
}
.card-image{
	image;
}
</style>

app/views/events/new.html.erb
<header class="header">
  <div>新規イベント作成</div>
</header>
<%= render 'form' %>

app/views/events/search.html.erb
<%= render "layouts/user-header"%>
<h1>検索結果</h1>
  <%= link_to "イベント一覧に戻る",events_path ,{class:"btn btn-primary"}%>
  <% @finding.each do |find| %>
  <div class="card" style="padding:10px">
    <div class="card-header">
      イベント名：<%= find.title%>
    </div>
    <div class="card-header">
      イベント主催者:<%= find.organizer.name%>
      <!--イベント主催者のプロフィールページに飛べるようにする-->
      <%#= link_to 'プロフィール', organizers_path(id: find.organizer.id), class: 'btn btn-info' %>
    </div>
    <div class="card-header">
      場所：<%= find.place%>
    </div>
    <div class="card-header">
      日程：<%= find.starttime%>
        （申し込み期限:<%= find.duedate%>）
    </div>
    <div class="card-header">
    <% if find.paticipants.count < find.number %>
      参加人数：<%= find.paticipants.count %>/<%= find.number %>
    <% else %>
      定員数に達したので、参加できません。（参加人数：<%= find.number %>）
    <% end%>
    </div>
    <% if find.image %>
      <%= image_tag(find.image, :class =>"card-image")%>
    <% end %>
    <div class="card-footer">
      <div class="picture-edit">
        <%= link_to '詳細', event_path(find.id),{class:"btn btn-primary"} %>
      </div>
    </div>
 </div>
<% end %>

app/views/events/searchOrganizer.html.erb
<%= render "layouts/admin-header"%>
<h1>検索結果</h1>
<%= link_to "イベント一覧に戻る",organizers_path ,{class:"btn btn-primary"}%>
<div>
			<div class="row">
				<% @finding.each do |find| %>
				<div class="col-xs-12 col-md-6 picture-panel">
					<div class="card" style="padding:10px">
						<div class="card-header">
					  イベント名：<%= find.title%>
	          </div>
				  <div class="card-header">
					  イベント主催者:<%= find.organizer.name%>
					<!--イベント主催者のプロフィールページに飛べるようにする-->
					<%#= link_to 'プロフィール', organizers_path(id: event.organizer.id), class: 'btn btn-info' %>
	        </div>
				  <div class="card-header">
				  	場所：<%= find.place%>
	        </div>
				  <div class="card-header">
					  日程：<%= find.startdate %>
						  （申し込み期限:<%=find.duedate %>）
	        </div>
				  <div class="card-header">
				  	<% if find.paticipants.count < find.number %>
	            参加人数：<%= find.paticipants.count %>/<%= find.number %>
	          <% else %>
	            定員数に達したので、参加できません。（参加人数：<%= find.number %>）
	          <% end%>
	        </div>
				  <div class="card-image">
				  <% if find.image %>
					  <%= image_tag(find.image,:width=>"600", height:"500")%>
				  <% else %>
				    <%= image_tag("noimage") %>
			    <% end %>
		     </div>
			   <div class="card-header">
				 <%= find.content%>
				   <div class="picture-edit">
             <% if  current_organizer.id == find.organizer_id  %>
             <%= link_to '削除',  event_path(find.id), method: :delete, data:{confirm: '本当に削除しますか？'},class: 'btn btn-danger' %>
             <%= link_to '編集',  edit_event_path(find.id), class: 'btn btn-info'  %>
              <% end %>
				   </div>
			   </div>
	     </div>
	  </div>
		 <% end %>
	 </div>
 </div>

app/views/events/searchUser.html.erb
<%= render "layouts/user-header"%>
<h1>検索結果</h1>
  <%= link_to "イベント一覧に戻る",events_path ,{class:"btn btn-primary"}%>
			<div class="row">
				<% @finding.each do |find| %>
				<div class="col-xs-12 col-md-6 picture-panel">
					<div class="card" style="padding:10px">
						<div class="card-header">
					  イベント名：<%= find.title%>
	          </div>
				  <div class="card-header">
					  イベント主催者:<%= find.organizer.name%>
					<!--イベント主催者のプロフィールページに飛べるようにする-->
					<%#= link_to 'プロフィール', organizers_path(id: event.organizer.id), class: 'btn btn-info' %>
	        </div>
				  <div class="card-header">
				  	場所：<%= find.place%>
	        </div>
				  <div class="card-header">
					  日程：<%= find.startdate %>
						  （申し込み期限:<%=find.duedate %>）
	        </div>
				  <div class="card-header">
				  	<% if find.paticipants.count < find.number %>
	            参加人数：<%= find.paticipants.count %>/<%= find.number %>
	          <% else %>
	            定員数に達したので、参加できません。（参加人数：<%= find.number %>）
	          <% end%>
	        </div>
				  <div class="card-image">
				  <% if find.image %>
					  <%= image_tag(find.image,:width=>"600", height:"500")%>
				  <% else %>
				    <%= image_tag("noimage") %>
			    <% end %>
		     </div>
			   <div class="card-header">
				 <%= find.content%>
				   <div class="picture-edit">
               <%= link_to '詳細', event_path(find.id),{class:"btn btn-primary"} %>
				   </div>
			   </div>
	     </div>
	  </div>
		 <% end %>
	 </div>
 </div>

app/views/events/show.html.erb
<%= render"layouts/user-header"%>
<div class="container">
  <div class="row">
    <div class="card">
      <div class="card-header">
        イベント名：<%= @event.title%>
      </div>
      <div class="card-header">
        場所：<%= @event.place%>
      </div>
      <div class="card-header">
        日程：<%= @event.startdate%><%= @event.starttime.strftime(" %H:%M")%>
         ~ <%= @event.enddate%><%= @event.endtime.strftime(" %H:%M")%>
        （申し込み期限:<%= @event.duedate%><%= @event.duetime.strftime(" %H:%M")%>）
      </div>
      <div class="card-header">
        <!-- 参加予定の人数をカウントして、追加する-->
        <% if @event.paticipants.count < @event.number %>
          参加人数：<%= @event.paticipants.count %>/<%= @event.number %>
        <% else %>
          定員数に達したので、参加できません。
        <% end%>
      </div>
      <% if @event.image %>
        <%= image_tag(@event.image, :class =>"card-image",:width=>"600", height:"500")%>
      <% end %>
      <div class="card-body"><%= @event.content%></div>
      <div class="card-footer">
        <div class="picture-edit">
          <%= render "reaction" %>
          <%= render "interest"%>
        </div>
      </div>
       <div class="card-footer">
          <p>コメント一覧</p>
            <div id="comments_area">
            <%= render partial: 'comments/index', locals: { comments: @comments, event: @event } %>
           </div>
           <%= render partial: 'comments/form', locals: { comment: @comment, event: @event} %>
      </div>
    </div>
  </div>
</div>