config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  authenticated :user do
    root :to => 'events#index'
  end

  devise_for :organizers, controllers: {
  sessions:      'organizers/sessions',
  passwords:     'organizers/passwords',
  registrations: 'organizers/registrations'
  }

  authenticated :organizer do
    root :to => "organizers#index"
  end
  root to: 'top#index'

  resources :users do
    collection do
      post :confirm
    end
  end
  get '/users/interests/:id', to:'users#interests'
  get '/users/bookmarks/:id', to:'users#bookmarks'
  get '/users/paticipants/:id', to:'users#paticipants'
  get '/users/followers/:id', to:'users#followers'

  resources :organizers do
    collection do
      post :confirm
    end
  end

  resources :events do
    resources :comments
    collection do
      post :confirm
    end
  end

  get 'searchUser', to:'events#searchUser'
  get 'searchOrganizer', to:'events#searchOrganizer'


  resources :interests, only: [:create, :destroy] # user can keep event as interests
  resources :bookmarks, only: [:create, :destroy]
  resources :paticipants, only: [:create, :destroy]
  resources :reactions, only: [:index, :create, :destroy]

  resources :chatusers do
    resources :chatmessages
  end
end

app/views/layouts/_admin-header.html.erb
<nav class="navbar navbar-expand-lg navbar-light admin-header-color">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if organizer_signed_in? %>
        <li><%= link_to "mypage", current_organizer, class: "nav-link" %></li>
        <li><%= link_to "Log out", destroy_organizer_session_path, method: :delete,class: "nav-link" %></li>
      <% else %>
        <li><%= link_to "Log in", new_organizer_session_path, class: "nav-link"%></li>
        <li><%= link_to "Sign up", new_organizer_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_user-header.html.erb
<nav class="navbar navbar-expand-lg navbar-light header-color">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li><%= link_to "mypage", current_user,class: "nav-link" %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete,class: "nav-link" %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path, class: "nav-link"%></li>
        <li><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsME</title>
    <%= csrf_meta_tags %>
    <meta name="current_user_id" content="<%= current_user.id if current_user %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-visit-control" content="reload">
  </head>

  <body>
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>